import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import Providers from "./providers";
import Navbar from "./navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Trion mart",
  description: "Generated by trion-mart",
  icons: {
    icon: '/icon.png', // or '/icon.png', '/icon.svg'
    
    
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          <main>{children}</main>
        </Providers>
        <footer className="border-t border-neutral-200 bg-white">
          <div className="mx-auto max-w-6xl px-6 py-10">
            <div className="grid gap-8 md:grid-cols-3">
              <div>
                <div className="text-lg font-semibold text-neutral-900">Trion Mart</div>
                <p className="mt-2 text-sm text-neutral-600">
                  Modern shopping experience built with Next.js.
                </p>
              </div>
              <div>
                <div className="text-sm font-medium text-neutral-900">Links</div>
                <ul className="mt-2 space-y-2 text-sm text-neutral-700">
                  <li>
                    <Link href="/products">Products</Link>
                  </li>
                  <li>
                    <Link href="/">Home</Link>
                  </li>
                  <li>
                    <Link href="/dashboard">Dashboard</Link>
                  </li>
                  <li>
                    <Link href="/login">Sign in</Link>
                  </li>
                </ul>
              </div>
              <div>
                <div className="text-sm font-medium text-neutral-900">Contact</div>
                <p className="mt-2 text-sm text-neutral-700">
                  support@trionmart.local
                </p>
              </div>
            </div>
            <div className="mt-8 border-t border-neutral-200 pt-6 text-sm text-neutral-600">
              © {new Date().getFullYear()} Trion Mart. All rights reserved.
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
